name: Build & Release (Tauri - Windows)

on:
  push:
    tags:
      - 'v*'   # runs when you push a tag like v0.1.0

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      # Build using the official Tauri action (respects beforeBuildCommand)
      - name: Build Tauri (Windows)
        uses: tauri-apps/tauri-action@v0
        with:
          releaseId: ${{ github.event.release.id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Attach artifacts even if no Release object exists yet
      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tauri-windows
          path: |
            src-tauri/target/release/bundle/**/*.msi
            src-tauri/target/release/bundle/**/*.exe
            src-tauri/target/release/bundle/**/*.zip
